<?php

// Data functions for table realtycontractpayments

// This script and data application were generated by AppGini 2.4 on 25/06/2003 at 19:54:53
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS;
	
	if(get_magic_quotes_gpc())
	{
		$contract_id = $HTTP_POST_VARS["contract_id"];
		$payment_date = $HTTP_POST_VARS["payment_date"];
		$amount = $HTTP_POST_VARS["amount"];
		$check_number = $HTTP_POST_VARS["check_number"];
		$check_bank = $HTTP_POST_VARS["check_bank"];
		$check_branch = $HTTP_POST_VARS["check_branch"];
	}
	else
	{
		$contract_id = addslashes($HTTP_POST_VARS["contract_id"]);
		$payment_date = addslashes($HTTP_POST_VARS["payment_date"]);
		$amount = addslashes($HTTP_POST_VARS["amount"]);
		$check_number = addslashes($HTTP_POST_VARS["check_number"]);
		$check_bank = addslashes($HTTP_POST_VARS["check_bank"]);
		$check_branch = addslashes($HTTP_POST_VARS["check_branch"]);
	}

	$da = explode("/",$payment_date);
	$payment_date = $da[2]."-".$da[1]."-".$da[0];

	sql("insert into realtycontractpayments (contract_id, payment_date, amount, check_number, check_bank, check_branch) values (" . (($contract_id != "") ? "'$contract_id'" : "NULL") . ", " . (($payment_date != "") ? "'$payment_date'" : "NULL") . ", " . (($amount != "") ? "'$amount'" : "NULL") . ", " . (($check_number != "") ? "'$check_number'" : "NULL") . ", " . (($check_bank != "") ? "'$check_bank'" : "NULL") . ", " . (($check_branch != "") ? "'$check_branch'" : "NULL") . ")");
	return mysql_insert_id();
}

function delete($selected_id)
{
	// insure referential integrity ...
	sql("delete from realtycontractpayments where id='$selected_id'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS;
	
	if(get_magic_quotes_gpc())
	{
		$contract_id = $HTTP_POST_VARS["contract_id"];
		$payment_date = $HTTP_POST_VARS["payment_date"];
		$amount = $HTTP_POST_VARS["amount"];
		$check_number = $HTTP_POST_VARS["check_number"];
		$check_bank = $HTTP_POST_VARS["check_bank"];
		$check_branch = $HTTP_POST_VARS["check_branch"];
	}
	else
	{
		$contract_id = addslashes($HTTP_POST_VARS["contract_id"]);
		$payment_date = addslashes($HTTP_POST_VARS["payment_date"]);
		$amount = addslashes($HTTP_POST_VARS["amount"]);
		$check_number = addslashes($HTTP_POST_VARS["check_number"]);
		$check_bank = addslashes($HTTP_POST_VARS["check_bank"]);
		$check_branch = addslashes($HTTP_POST_VARS["check_branch"]);
	}
	$da = explode("/",$payment_date);
	$payment_date = $da[2]."-".$da[1]."-".$da[0];

	sql("update realtycontractpayments set contract_id=" . (($contract_id != "") ? "'$contract_id'" : "NULL") . ", payment_date=" . (($payment_date != "") ? "'$payment_date'" : "NULL") . ", amount=" . (($amount != "") ? "'$amount'" : "NULL") . ", check_number=" . (($check_number != "") ? "'$check_number'" : "NULL") . ", check_bank=" . (($check_bank != "") ? "'$check_bank'" : "NULL") . ", check_branch=" . (($check_branch != "") ? "'$check_branch'" : "NULL") . " where id='$selected_id'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	global $userID, $FilterValue1,$lang;
	$code = "<br><table border=1 bordercolor=silver cellpadding=0 cellspacing=0><tr><td bgcolor=#efefef><div class=TableTitle>Detail View</div></td></tr><tr><td><table>";
	$code .= "\n\t<tr><td colspan=2></td><td rowspan=70 valign=top>";
	if($AllowInsert)
		$code .= "<div><a href='realtycontracts_view.php?SelectedID=$FilterValue1'><img src=contract.gif border=0></a></div><br>";
		$code .= "<div><input vspace=1 type=image src=insert.gif name=insert alt='Add New Record'></div>";
	
	// combobox: contract_id
	$combo_contract_id = new DataCombo;
	$combo_contract_id->Query = "select id, contract_number from realtycontracts where user_id = $userID order by contract_number";
	$combo_contract_id->SelectName = "contract_id";

	if($selected_id)
	{
		$res = sql("select * from realtycontractpayments where id='$selected_id'");
		$row = mysql_fetch_object($res);
		$da=explode("-",$row->payment_date);
		$row->payment_date=$da[2]."/".$da[1]."/".$da[0];
		$combo_contract_id->SelectedData = $row->contract_id;

		$code .= "<br>";
		if($AllowUpdate)
			$code .= "<div><input type=image src=update.gif vspace=1 name=update alt='Update Record'></div>";
		if($AllowDelete)
			$code .= "<div><input type=image src=delete.gif  vspace=1 name=delete alt='Delete Record' onclick='return confirm(\"Are you sure you want to delete this record permanently?\");'></div>";
		$code .= "<div><input type=image src=cancel_search.gif  vspace=1 name=deselect alt='Deselect Record'></div>";
	}
	$combo_contract_id->Render();

	$code .= "</td></tr>";


	// Detail view form fields
	//$code .= "\n\t<tr><td class=TableHeader valign=top><div class=TableHeader style='text-align:right;'>Code</div></td><td class=TableBody>$row->id&nbsp;&nbsp;</td></tr>";
	$code .= "\n\t<tr><td class=TableHeader valign=top><div class=TableHeader style='text-align:right;'>".$lang[contract]."</div></td><td>$combo_contract_id->HTML&nbsp;&nbsp;</td></tr>";
	$code .= "\n\t<tr><td class=TableHeader valign=top><div class=TableHeader style='text-align:right;'>".$lang['date']."</div></td><td ><input size=10 type=text class=TextBox name=payment_date value='$row->payment_date'> (dd/mm/yyyy)&nbsp;&nbsp;</td></tr>";
	$code .= "\n\t<tr><td class=TableHeader valign=top><div class=TableHeader style='text-align:right;'>".$lang[amount]."</div></td><td ><input size=10 type=text class=TextBox name=amount value='$row->amount'>&nbsp;&nbsp;</td></tr>";
	$code .= "\n\t<tr><td class=TableHeader valign=top><div class=TableHeader style='text-align:right;'>".$lang[check_number]."</div></td><td ><input size=10 type=text class=TextBox name=check_number value='$row->check_number'>&nbsp;&nbsp;</td></tr>";
	$code .= "\n\t<tr><td class=TableHeader valign=top><div class=TableHeader style='text-align:right;'>".$lang[bank]."</div></td><td ><input size= 50 type=text class=TextBox name=check_bank value='$row->check_bank'>&nbsp;&nbsp;</td></tr>";
	$code .= "\n\t<tr><td class=TableHeader valign=top><div class=TableHeader style='text-align:right;'>".$lang[branch]."</div></td><td ><input size= 50 type=text class=TextBox name=check_branch value='$row->check_branch'>&nbsp;&nbsp;</td></tr>";

	$code .= "</table></td></tr></table></center>";

	return $code;
}
?>