<?php
// This script and data application were generated by AppGini 2.4 on 25/06/2003 at 19:54:53
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include("./lib.php");
	include("./listingsdb_dml.php");
	
	$x = new DataList;
	if($HTTP_POST_VARS["Filter_x"] != "")
	{
		// Query used in filters page
		$x->Query = "select listingsdb.id as 'Id', listingsdb.title as 'Title' from listingsdb";
	}
	else
	{
		// Query used in table view
		$x->Query = "select listingsdb.id as 'Id', listingsdb.title as 'Title' from listingsdb";
	}
	$x->DataHeight = 150;
	$x->AllowSelection = 1;
	$x->AllowDelete = 1;
	$x->AllowInsert = 1;
	$x->AllowUpdate = 1;
	$x->AllowFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 0;
	$x->HideTableView = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 0;
	$x->QuickSearchText = "Quick search";
	$x->ScriptFileName = "listingsdb_view.php";
	$x->TableTitle = "Listingsdb";
	$x->PrimaryKey = "listingsdb.id";
	$x->ColWidth[] = 150;
	$x->ColWidth[] = 150;
	$x->Render();
	
	echo $x->HTML;
?>