<?php
// This script and data application were generated by AppGini 2.4 on 25/06/2003 at 19:54:53
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include("include/lib.php");
	include("./realtycontracts_dml.php");
	
	$x = new DataList;
	if($HTTP_POST_VARS["Filter_x"] != "")
	{
		// Query used in filters page
		$x->Query = "select realtycontracts.contract_number as '".$lang[number]."', realtycontracts.customer as '".$lang[customer]."', listingsDB3.title as  '".$lang[listing]."', realtycontracts.term as '".$lang[term]."', realtycontracts.amount as  '".$lang[amount]."', realtycontracts.currency as  '".$lang[currency]."' from realtycontracts, listingsDB as listingsDB3 where realtycontracts.user_id=$userID and realtycontracts.listingid=listingsDB3.id";
	}
	else
	{
		// Query used in table view
		$x->Query = "select realtycontracts.contract_number as  '".$lang[number]."', realtycontracts.customer as '".$lang[customer]."', listingsDB3.title as  '".$lang[listing]."', realtycontracts.term as  '".$lang[term]."', realtycontracts.amount as  '".$lang[amount]."', realtycontracts.currency as  '".$lang[currency]."', realtycontracts.usd_rate as  '".$lang[usd_rate]."' from realtycontracts, listingsDB as listingsDB3 where realtycontracts.user_id=$userID  and realtycontracts.listingid=listingsDB3.id";
	}
	$x->DataHeight = 98;
	$x->AllowSelection = 1;
	$x->AllowDelete = 1;
	$x->AllowInsert = 1;
	$x->AllowUpdate = 1;
	$x->AllowFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->HideTableView = 0;
	$x->RecordsPerPage = 5;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $lang[search];
	$x->ScriptFileName = "realtycontracts_view.php";
	$x->TableTitle = $lang[admin_menu_edit_contracts];
	$x->PrimaryKey = "realtycontracts.id";
	$x->ColWidth[] = 30;
	$x->ColWidth[] = 150;
	$x->ColWidth[] = 150;
	$x->ColWidth[] = 80;
	$x->ColWidth[] = 100;
	$x->ColWidth[] = 40;
	$x->ColWidth[] = 100;
	$x->Render();
	
	echo $x->HTML;
	
	include("$config[template_path]/admin_bottom.html");
	$conn->Close(); // close the db connection
?>