<?php

// Data functions for table listingsDB

// This script and data application were generated by AppGini 2.4 on 25/06/2003 at 19:54:53
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS;
	
	if(get_magic_quotes_gpc())
	{
		$id = $HTTP_POST_VARS["id"];
		$title = $HTTP_POST_VARS["title"];
	}
	else
	{
		$id = addslashes($HTTP_POST_VARS["id"]);
		$title = addslashes($HTTP_POST_VARS["title"]);
	}
	if($id == "") {echo StyleSheet() . "\n\n<div class=Error>Error: 'Id' field is a primary key field and cannot be empty.</div>"; exit;}

	
	sql("insert into listingsDB (id, title) values (" . (($id != "") ? "'$id'" : "NULL") . ", " . (($title != "") ? "'$title'" : "NULL") . ")");
	return $id;
}

function delete($selected_id)
{
	// insure referential integrity ...
	// child table: realtycontracts
	$res = sql("select id from listingsDB where id='$selected_id'");
	$id = mysql_fetch_row($res);
	$rires = sql("select count(1) from realtycontracts where listingid='$id[0]'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0])
	{
		return "Couldn't delete record due to presence of $rirow[0] related record(s) in table 'realtycontracts'";
	}
	
	sql("delete from listingsDB where id='$selected_id'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS;
	
	if(get_magic_quotes_gpc())
	{
		$id = $HTTP_POST_VARS["id"];
		$title = $HTTP_POST_VARS["title"];
	}
	else
	{
		$id = addslashes($HTTP_POST_VARS["id"]);
		$title = addslashes($HTTP_POST_VARS["title"]);
	}

	sql("update listingsDB set id=" . (($id != "") ? "'$id'" : "NULL") . ", title=" . (($title != "") ? "'$title'" : "NULL") . " where id='$selected_id'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	
	$code = "<center><br><table border=1 bordercolor=navy cellpadding=0 cellspacing=0><tr><td><div class=TableTitle>Detail View</div></td></tr><tr><td><table>";
	$code .= "\n\t<tr><td colspan=2></td><td rowspan=7 valign=top>";
	if($AllowInsert)
		$code .= "<div><input type=image src=insert.gif name=insert alt='Add New Record'></div>";
	

	if($selected_id)
	{
		$res = sql("select * from listingsDB where id='$selected_id'");
		$row = mysql_fetch_object($res);

		$code .= "<br>";
		if($AllowUpdate)
			$code .= "<div><input type=image src=update.gif name=update alt='Update Record'></div>";
		if($AllowDelete)
			$code .= "<div><input type=image src=delete.gif name=delete alt='Delete Record' onclick='return confirm(\"Are you sure you want to delete this record permanently?\");'></div>";
		$code .= "<div><input type=image src=cancel_search.gif name=deselect alt='Deselect Record'></div>";
	}

	$code .= "</td></tr>";


	// Detail view form fields
	$code .= "\n\t<tr><td class=TableHeader valign=top><div class=TableHeader style='text-align:right;'>Id</div></td><td class=TableBody><input size=10 type=text class=TextBox name=id value='$row->id'>&nbsp;&nbsp;</td></tr>";
	$code .= "\n\t<tr><td class=TableHeader valign=top><div class=TableHeader style='text-align:right;'>Title</div></td><td class=TableBody><input size=10 type=text class=TextBox name=title value='$row->title'>&nbsp;&nbsp;</td></tr>";

	$code .= "</table></td></tr></table></center>";

	return $code;
}
?>