<?php
// This script and data application were generated by AppGini 2.4 on 25/06/2003 at 19:54:53
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include("include/lib.php");
	include("./realtycontractpayments_dml.php");
	
	$x = new DataList;
	if($HTTP_POST_VARS["Filter_x"] != "")
	{
		// Query used in filters page
		$x->Query = "select realtycontracts2.contract_number as '".$lang[contract]."', DATE_FORMAT(realtycontractpayments.payment_date,'%d/%m/%y') as '".$lang[date]."', realtycontractpayments.amount as '".$lang[amount]."', realtycontractpayments.check_number as '".$lang[check_number]."', realtycontractpayments.check_bank as '".$lang[bank]."', realtycontractpayments.check_branch as '".$lang[branch]."' from realtycontractpayments, realtycontracts as realtycontracts2 where realtycontracts2.user_id=$userID and  realtycontractpayments.contract_id=realtycontracts2.id";
	}
	else
	{
		// Query used in table view
		$x->Query = "select realtycontracts2.contract_number as '".$lang[contract]."', DATE_FORMAT(realtycontractpayments.payment_date,'%d/%m/%y') as '".$lang[date]."', realtycontractpayments.amount as '".$lang[amount]."', realtycontractpayments.check_number as '".$lang[check_number]."', realtycontractpayments.check_bank as '".$lang[bank]."', realtycontractpayments.check_branch as '".$lang[branch]."' from realtycontractpayments, realtycontracts as realtycontracts2 where realtycontracts2.user_id=$userID and realtycontractpayments.contract_id=realtycontracts2.id";
	}
	$x->DataHeight = 98;
	$x->AllowSelection = 1;
	$x->AllowDelete = 1;
	$x->AllowInsert = 1;
	$x->AllowUpdate = 1;
	$x->AllowFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->HideTableView = 0;
	$x->RecordsPerPage = 5;
	$x->QuickSearch = 0;
	$x->QuickSearchText = $lang[search];
	$x->ScriptFileName = "realtycontractpayments_view.php";
	$x->TableTitle = $lang[payments];
	$x->PrimaryKey = "realtycontractpayments.id";
	$x->ColWidth[] = 50;
	$x->ColWidth[] = 120;
	$x->ColWidth[] = 80;
	$x->ColWidth[] = 150;
	$x->ColWidth[] = 150;
	$x->ColWidth[] = 150;
	$x->Render();
	
	echo $x->HTML;
	
		include("$config[template_path]/admin_bottom.html");
	$conn->Close(); // close the db connection
?>