<?php
// This script and data application were generated by AppGini 2.4 on 25/06/2003 at 19:54:53
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include("./lib.php");
	include("./realtycontracts_dml.php");
	
	$x = new DataList;
	if($HTTP_POST_VARS["Filter_x"] != "")
	{
		// Query used in filters page
		$x->Query = "select realtycontracts.contract_number as 'Number', realtycontracts.customer as 'Customer', listingsdb3.title as 'Listing', realtycontracts.term as 'Term', realtycontracts.amount as 'Amount', realtycontracts.currency as 'Currency' from realtycontracts, listingsdb as listingsdb3 where realtycontracts.listingid=listingsdb3.id";
	}
	else
	{
		// Query used in table view
		$x->Query = "select realtycontracts.contract_number as 'Number', realtycontracts.customer as 'Customer', listingsdb3.title as 'Listing', realtycontracts.term as 'Term', realtycontracts.amount as 'Amount', realtycontracts.currency as 'Currency', realtycontracts.usd_rate as 'USD Rate' from realtycontracts, listingsdb as listingsdb3 where realtycontracts.listingid=listingsdb3.id";
	}
	$x->DataHeight = 75;
	$x->AllowSelection = 1;
	$x->AllowDelete = 1;
	$x->AllowInsert = 1;
	$x->AllowUpdate = 1;
	$x->AllowFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->HideTableView = 0;
	$x->RecordsPerPage = 5;
	$x->QuickSearch = 3;
	$x->QuickSearchText = "Quick search";
	$x->ScriptFileName = "realtycontracts_view.php";
	$x->TableTitle = "Contracts";
	$x->PrimaryKey = "realtycontracts.id";
	$x->ColWidth[] = 30;
	$x->ColWidth[] = 150;
	$x->ColWidth[] = 150;
	$x->ColWidth[] = 80;
	$x->ColWidth[] = 100;
	$x->ColWidth[] = 40;
	$x->ColWidth[] = 100;
	$x->Render();
	
	echo $x->HTML;
?>